### ISSUE TITLE
SVG morph resets animation

### ISSUE THREAD

**Issue by dellfort** [jepiqueau/jeep#14]
Hi.

**Current behavior:**
When I trigger a morph on an path, then it resets the animation to the starting state, after the animation is complete.
No option (that I'm aware of) that allows stops the animation to reset on the end

**Expected behavior:**
have an option that after the animation ended, the end status stays, and no reset happens

**Comment by jepiqueau** [comment]
@dellfort  Hi, thanks for using the component. I do not quite understand your question, there is no reset of the animation to the starting state. In the examples i gave i copied the first element at the end in order to have a smooth transition when the `repeatcount` parameter is > 1. If you set the `repeatcount` parameter to 1 and have a `last path` different of the `first path` you will see that the animation stays to the end. So give me more explanations if still required

**Comment by jepiqueau** [comment]
@dellfort I didn't hear anything from you, can you close the issue if you do not have any problem

**Comment by dellfort** [comment]
I think there was an misunderstanding from my site. Thanks for your efforts
